### ISSUE TITLE
docs with CCU params

### ISSUE THREAD

**Issue by flugi** [tomtom1976/Blackmagic-Decklink-CCU#1]
Hello,

I was wondering what kind of documentation were you using to create CCU ancillary data. I downloaded the recent documentation from BMD page (DeckLink SDK Docs) , and I just don't find it.

**Comment by tomtom1976** [comment]
The CCU ancillary data are in the Camera  manual.

https://www.blackmagicdesign.com/manuals/CinemaCamera/Blackmagic_Studio_Camera_Manual.pdf

**Comment by flugi** [comment]
Thanks!
