### ISSUE TITLE
How to use all this code ?

### ISSUE THREAD

**Issue by Sebosebhosh** [tomtom1976/Blackmagic-Decklink-CCU#2]
Hi @tomtom1976 ,

Your project is exactly what I need for my mini studio. But I really dont know how to use all of this ...
Should I be using this in an other app ?
I am very sorry to ask this : could you tell me how I should use all the file in the repositery ?

Thank you for your time and your project.

Seb

**Comment by tomtom1976** [comment]
Hi,

This is a complete VB# Application with UI. You may only have to take out the parts that you need. The whole thing was just a feasibility study. At the moment we only use the tally part to include the signal.

To use this code open the solution in Visual Studio and compile it. Maybe you need to adjust path to Blackmagic SDK maybe.

If you need other things , let me check our latest resoucres. So let me know.

Thomas

**Comment by Sebosebhosh** [comment]
Thank you for all the info !
